# -*- coding: utf-8 -*-
"""whisper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCYKoFp4xa1ShisVX92gV7r9GU5JZ0j9
"""

!pip install -U openai-whisper

import whisper
model = whisper.load_model('base')

results= model.transcribe('test_audio.ogg',fp16=False)

results['text']